### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by carton04** [carton04/furima-38626#22]
#URL
https://furima-38626.onrender.com
#Basic認証ID,password
admin
2222
#出品者用のメールアドレスとパスワード
test@test.com
aaa111
#購入者用のメールアドレスとパスワード
test2@test.com
aaa111

**Comment by snkw-works** [comment]
@carton04 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されるよう修正しましょう**
「新品・未使用」が正しく表示されていない状態です。
![スクリーンショット_2022-11-16_14_55_36](https://user-images.githubusercontent.com/54050089/202096912-10f9e3a7-234f-4414-8ce4-5df39cd46d4f.jpg)

- [ ] **商品購入ページにて、商品出品時に登録した情報のうち、「商品名・商品画像・価格・配送料の負担」の4つの情報が、見本アプリと同様の形で表示されるよう修正しましょう**
「価格」が正しく表示されていない状態です。
![スクリーンショット_2022-11-16_14_58_58](https://user-images.githubusercontent.com/54050089/202096645-9cb250cd-7c39-4ada-80a7-2f06e941f393.jpg)


【補足】
現在、出品画面の「配送料の負担」の「（）」が全角と半角が混ざって表示されています。必須要件とはなっておりませんが、可能であれば全角/半角のどちらかに統一するようにしましょう。
<img width="411" alt="スクリーンショット 2022-11-16 15 03 08" src="https://user-images.githubusercontent.com/54050089/202097625-58517037-f391-47a3-8801-927f56a17fd1.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ghost** [comment]
@carton04 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。

![最終課題LGTM](https://user-images.githubusercontent.com/116065064/202104264-bbb0fa6a-7e25-444a-a799-bf20dbac9550.png)
